server.port: 8080

polaris.app.version: @project.version@

logging:
#  file: logs/ci-manager.log
  level:
    org.springframework.web: info
    com.atsistemas: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
